#!/usr/bin/env python3
"""Convert the fixed-address SH-4 widescreen helpers into Flycast writes."""

from __future__ import annotations

from pathlib import Path
import re
import sys


WRITE_ALIAS = 0x80000000
SYMBOL_PATTERN = re.compile(
    r"^([0-9a-fA-F]+)\s+\w\s+(gdx_widescreen_[A-Za-z0-9_]+)$"
)
SEGMENTS = (
    ("transition", 0x0C4F0590, 0xB0),
    ("result", 0x0C4F0640, 0xC0),
    ("hud", 0x0C4F0700, 0x100),
)


def main() -> None:
    if len(sys.argv) != 6:
        raise SystemExit(
            "usage: conv_widescreen.py <transition.bin> <result.bin> "
            "<hud.bin> <nm> <output>"
        )

    payloads: list[tuple[str, int, bytes]] = []
    for (name, address, maximum_size), path in zip(SEGMENTS, sys.argv[1:4]):
        payload = Path(path).read_bytes()
        if len(payload) % 2:
            raise SystemExit(f"{name} payload is not 16-bit aligned")
        if len(payload) > maximum_size:
            raise SystemExit(
                f"{name} payload is {len(payload)} bytes; maximum is {maximum_size}"
            )
        payloads.append((name, address, payload))

    symbols: list[tuple[int, str]] = []
    for line in Path(sys.argv[4]).read_text(encoding="utf-8").splitlines():
        match = SYMBOL_PATTERN.match(line)
        if match:
            symbols.append((int(match.group(1), 16), match.group(2)))

    lines = [
        "// Generated by gdxsv_patch/build_widescreen.sh.",
        "// Fixed load range: 0x0c4f0590..0x0c4f07b3.",
    ]
    for address, name in symbols:
        lines.append(f'symbols_["{name}"] = 0x{address:08x};')
    for name, load_address, payload in payloads:
        lines.append(f"// {name}: 0x{load_address:08x}, {len(payload)} bytes.")
        for offset in range(0, len(payload), 2):
            word = int.from_bytes(payload[offset : offset + 2], "little")
            address = load_address + WRITE_ALIAS + offset
            lines.append(f"gdxsv_WriteMem16(0x{address:08x}u, 0x{word:04x}u);")
    lines.append("")
    Path(sys.argv[5]).write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
